// This file is auto-generated by @hey-api/openapi-ts

import type { ListVacationsResponse } from "./types.gen";

const vacationSchemaResponseTransformer = (data: any) => {
  data.end_date = new Date(data.end_date);
  data.start_date = new Date(data.start_date);
  return data;
};

export const listVacationsResponseTransformer = async (
  data: any,
): Promise<ListVacationsResponse> => {
  data = data.map((item: any) => vacationSchemaResponseTransformer(item));
  return data;
};
